### ISSUE TITLE
is there a way to run this only for changed files or specific files

### ISSUE THREAD

**Issue by agiratech-vigneshm** [jeroenouw/tscov#1]
Imagine I want to use this as a pre-push hook which checks and enforces the type coverage limit on VCS level. Is there an easy way to run this on specific files or only on changed files (VCS). I looked at the docs and couldn't find any. I Looked through the code to see if I can do it, but I realized I am not strong enough in how TSC works to understand your code.

Is there any thoughts on adding this as a feature?

**Comment by farisT** [comment]
> Imagine I want to use this as a pre-push hook which checks and enforces the type coverage limit on VCS level. Is there an easy way to run this on specific files or only on changed files (VCS). I looked at the docs and couldn't find any. I Looked through the code to see if I can do it, but I realized I am not strong enough in how TSC works to understand your code.
> 
> Is there any thoughts on adding this as a feature?

Hello! 

I have made a pull request to the repo to clarify the documentation on how tsdoc works with specific folders or files.

by using :

`tscov -p YOURFOLDERNAME`

you can test for specific folders and also refer to files within that folder.

`tscov -p YOURFOLDERNAME/YOURFILENAME.ts`

**Comment by agiratech-vigneshm** [comment]
@farisT Thanks for your help. I'll try it. @jeroenouw I am closing this.

**Comment by farisT** [comment]
@agiratech-vigneshm sorry I was mistaken about testing the specific filename, I thought it already existed but it didnt so I built it now.

I have a PR waiting for approval https://github.com/jeroenouw/tscov/pull/3
